### ISSUE TITLE
Issue running run_mc_anisotropic.sh on linux

### ISSUE THREAD

**Issue by MatthewBM** [ilastik/nature_methods_multicut_pipeline#3]
Hello, 

as a preface I am using CPLEX V1.6.3 Developer's Edition

I retrieved the multi-cut software from the supplemental repository that was pointed to by the Nature paper and am trying to run 'run_mc_anisotropic' with lifted=True and SNEMI=true on the tutorial data. I have been successful in running your software locally on windows with example data and my data but need this to scale to a linux computing cluster so I'm running the tutorial again on linux.

Your nature linux repo has symbolic link issues as the package is configured as if CPLEX is already installed in the release prior to linking it, causing multicut to reference CPLEX files that don't exist, I fixed this by running:
unlink /multicut-software/lib/libconcert.so
unlink /multicut-software/lib/libcplex.so
unlink /multicut-software/lib/libilocplex.so

I got all of the same errors/issues in sequence that are mentioned in Issue #1. The Dev mentioned in that thread that they were committing updates but that's where I am having trouble. Are these updates to the github repo? It doesn't look built for linux and the build script doesn't work.

I have been copying scripts from the github into the software as I get traceback errors in an attempt to update it (hence getting all the errors mentioned in the previous issue submission) but here's where I'm at with that: 

Thanks in advance and I am very excited to get this working.

```
Warning: TIFFDecoder: no TIFFTAG_SAMPLEFORMAT or TIFFTAG_DATATYPE, guessing pixeltype 'UINT16'.
Warning: TIFFDecoder: no TIFFTAG_SAMPLEFORMAT or TIFFTAG_DATATYPE, guessing pixeltype 'UINT16'.
python: /miniconda/conda-bld/graph_1480389181293/work/dependencies/graph-1.6/include/andres/graph/graph.hxx:329: std::size_t andres::graph::Graph<VISITOR>::insertEdge(std::size_t, std::size_t) [with VISITOR d int]: Assertion `vertexIndex0 < numberOfVertices()' failed.
Starting Lifted Multicut Workflow
Calculating filter in 3d, with anisotropy factor: 5.0
Calculating filter in 3d, with anisotropy factor: 5.0
Calculating filter in 3d, with anisotropy factor: 5.0
Calculating filter in 3d, with anisotropy factor: 5.0
Running lifted multicut on ds_test
Weights learned on ds_train
Start learning
Computing:  compute_and_save_lifted_nh with args:
(0, 3)
Results will be written in  /oasis/scratch/comet/mmadany/temp_project/MultiCut/UPDATEFIX_Job6_LiftedSnemi/cache/ds_test/compute_and_save_lifted_nh_0_3.h5 data
Computing RAG for seg_id 0
WRITING IN  /oasis/scratch/comet/mmadany/temp_project/MultiCut/UPDATEFIX_Job6_LiftedSnemi/cache/ds_test/rag_seg0.h5 rag
run_mc_anisotropic.sh: line 5: 127773 Aborted                 ${PREFIX}/bin/python ${PREFIX}/scripts/run_mc_anisotropic.py "$@"
```

**Comment by constantinpape** [comment]
Hi Matthew,

the issue you are running into is not connected to cplex, but rather this:
```
python: /miniconda/conda-bld/graph_1480389181293/work/dependencies/graph-1.6/include/andres/graph/graph.hxx:329: std::size_t andres::graph::Graph::insertEdge(std::size_t, std::size_t) [with VISITOR d int]: Assertion `vertexIndex0 < numberOfVertices()' failed.
```
This indicates that something with the superpixels is off.
What data are you running this on? You could try to run with `SNEMI=false`, because this does something fishy with superpixels as far as I remember.

In general, we moved quite far along with the code-base since the paper.
If you are trying to use multicut for larger datasets, it would make sense for you to have a look into the new versions of this as well, but I can tell you more if you let us know what kind of data you want to use Multicut for.

**Comment by MatthewBM** [comment]
I was trying to use the tutorial data. Where is the code-base that has moved along? Is it part of the Ilastik packages somewhere?

**Comment by constantinpape** [comment]
I am pretty sure this issue error:

> python: /miniconda/conda-bld/graph_1480389181293/work/dependencies/graph-1.6/include/andres/graph/graph.hxx:329: std::size_t andres::graph::Graph<VISITOR>::insertEdge(std::size_t, std::size_t) [with VISITOR d int]: Assertion `vertexIndex0 < numberOfVertices()' failed.

is caused by an over-segmentation labeling that is not consecutive.
Just save the oversegmentation again, but this time with consecutive labeling and it should work.
You can use `vigra.analysis.relabelConsecutive` for this.


> I was trying to use the tutorial data. Where is the code-base that has moved along? Is it part of the Ilastik packages somewhere?

All the c++ implementations for the multicut functionality have moved to nifty:
https://github.com/constantinpape/nifty
There is an ilastik workflow for multicut now:
https://www.ilastik.org/documentation/multicut/multicut
And my code to run it for large volumes:
https://github.com/constantinpape/cluster_tools
